# Generated by Django 2.2.24 on 2022-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lecturer', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
